gerenciamento/urls.py
"""Define os URL patterns de gerenciamento."""

from django.urls import path
from . import views
from gerenciamento.views import ResetPasswordView
from django.contrib.auth import views as auth_views

app_name = 'gerenciamento'

urlpatterns = [
    # Pagina inicial
    path('', views.index, name='index'),
    # Pagina inicial admin
    path('iadmin/', views.indexadmin, name='indexadmin'),
    # Pagina de cadastro dos motoristas
    path('cadastrarm/', views.cadastrarm, name='cadastrarm'),
    # Pagina de sucesso
    path('sucesso/', views.sucesso, name='sucesso'),
    # Pagina de sucesso
    path('pesquisarm/', views.pesquisarm, name='pesquisarm'),
    # Pagina de edição dos motoristas
    path('editarm/', views.editarm, name='editarm'),
    # Pagina inserção dos dados da edição dos motoristas
    path('formeditarm/<str:cpf_motorista>/', views.formeditarm, name='formeditarm'),
    # Pagina de exclusão dos motoristas
    path('excluirm/', views.excluirm, name='excluirm'),
    # Pagina de exclusão dos motoristas
    path('excluirm/<str:cpf_motorista>/', views.formexcluirm, name='formexcluirm'),
    # Pagina de cadastro dos usuarios
    path('cadastraru/', views.cadastraru, name='cadastraru'),
    # Pagina de login
    path('login/', views.login_view, name='login'),
    # Pagina de logout
    path('logout/', views.logout_view, name='logout'),
    # Pagina de inserção do email para a redefinição de senha
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    # Pagina de redefinição da senha do usuario
    path('password-reset-confirm/<str:email>/', views.custom_password_reset_confirm, name='redefinir_senha'),
    # Pagina de sucesso da redefinação da senha
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='gerenciamento/login/password_reset_complete.html'),
    name='password_reset_complete'),
    # Pagina de cadastro dos cartões
    path('cadastrarc/', views.cadastrarc, name='cadastrarc'),
    # Pagina de pesquisa dos cartões
    path('pesquisarc/', views.pesquisarc, name='pesquisarc'),
    # Pagina de edição dos cartões
    path('editarc/', views.editarc, name='editarc'),
    # Pagina inserção dos dados da edição dos cartões
    path('formeditarc/<str:numero_conta>/', views.formeditarc, name='formeditarc'),
    # Pagina de exclusão dos cartões
    path('excluirc/', views.excluirc, name='excluirc'),
    # Pagina de exclusão dos cartões
    path('excluirc/<str:numero_conta>/', views.formexcluirc, name='formexcluirc'),
    # Pagina de pesquisa dos usuarios
    path('pesquisaru/', views.pesquisaru, name='pesquisaru'),
    # Pagina de edição dos usuarios
    path('editaru/', views.editaru, name='editaru'),
    # Pagina inserção dos dados da edição dos usuarios
    path('formeditaru/<str:cpf_fiscal>/', views.formeditaru, name='formeditaru'),
    # Pagina de exclusão dos usuarios
    path('excluiru/', views.excluiru, name='excluiru'),
    # Pagina de exclusão dos usuarios
    path('excluiru/<str:cpf_fiscal>/', views.formexcluiru, name='formexcluiru'),
    # Pagina de cadastro dos tipos de veículos
    path('cadastrart/', views.cadastrart, name='cadastrart'),
    # Pagina de pesquisa dos tipos de veículos
    path('pesquisart/', views.pesquisart, name='pesquisart'),
    # Pagina de edição dos tipos de veículos
    path('editart/', views.editart, name='editart'),
    # Pagina inserção dos dados da edição dos tipos de veículos
    path('formeditart/<str:id_tipo>/', views.formeditart, name='formeditart'),
    # Pagina de exclusão dos tipos de veículos
    path('excluirt/', views.excluirt, name='excluirt'),
    # Pagina de exclusão dos motoristas
    path('excluirt/<str:id_tipo>/', views.formexcluirt, name='formexcluirt'),
    # Pagina de cadastro dos veículos
    path('cadastrarv/', views.cadastrarv, name='cadastrarv'),
    # Pagina de pesquisa dos tipos de veículos
    path('pesquisarv/', views.pesquisarv, name='pesquisarv'),
    # Pagina de edição dos tipos de veículos
    path('editarv/', views.editarv, name='editarv'),
    # Pagina inserção dos dados da edição dos tipos de veículos
    path('formeditarv/<str:renavam>/', views.formeditarv, name='formeditarv'),
    # Pagina de exclusão dos tipos de veículos
    path('excluirv/', views.excluirv, name='excluirv'),
    # Pagina de exclusão dos motoristas
    path('excluirv/<str:renavam>/', views.formexcluirv, name='formexcluirv'),
    # Pagina de cadastro dos veículos
    path('cadastrarf/', views.cadastrarf, name='cadastrarf'),
    # Pagina de pesquisa dos tipos de veículos
    path('pesquisarf/', views.pesquisarf, name='pesquisarf'),
    # Pagina de edição dos tipos de veículos
    path('editarf/', views.editarf, name='editarf'),
    # Pagina inserção dos dados da edição dos tipos de veículos
    path('formeditarf/<str:id_frete>/', views.formeditarf, name='formeditarf'),
    # Pagina de exclusão dos tipos de veículos
    path('excluirf/', views.excluirf, name='excluirf'),
    # Pagina de exclusão dos motoristas
    path('excluirf/<str:id_frete>/', views.formexcluirf, name='formexcluirf'),
    # Pagina de cadastro dos veículos
    path('cadastrarp/', views.cadastrarp, name='cadastrarp'),
    # Pagina de pesquisa dos tipos de veículos
    path('pesquisarp/', views.pesquisarp, name='pesquisarp'),
    # Pagina de edição dos tipos de veículos
    path('editarp/', views.editarp, name='editarp'),
    # Pagina inserção dos dados da edição dos tipos de veículos
    path('formeditarp/<str:id_pagamento>/', views.formeditarp, name='formeditarp'),
    # Pagina de exclusão dos tipos de veículos
    path('excluirp/', views.excluirp, name='excluirp'),
    # Pagina de exclusão dos motoristas
    path('excluirp/<str:id_pagamento>/', views.formexcluirp, name='formexcluirp'),
]

sgf_project/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerenciamento.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gerenciamento/models.py
from django.db import models

from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.utils.translation import gettext_lazy as _


class Motorista(models.Model):
    cpf_motorista = models.CharField(db_column='cpf_motorista',max_length=11,primary_key=True)
    registro_cnh = models.CharField(max_length=11)
    nome = models.CharField(max_length=50)
    telefone = models.CharField(max_length=11)
    endereco = models.CharField(max_length=50)
    data_admissao = models.DateField()

    class Meta:
        managed = False
        db_table = 'motorista'

    def __str__(self):
        return self.cpf_motorista

class Cartao(models.Model):
    agencia = models.CharField(max_length=5)
    cpf_motorista = models.ForeignKey(Motorista,db_column="cpf_motorista",on_delete=models.SET_DEFAULT,default="0")
    numero_conta = models.CharField(max_length=6,primary_key=True)
    validade = models.DateField()
    
    class Meta:
        managed = False
        db_table = 'cartao'

    def __str__(self):
        return self.numero_conta

class MinhaGestaoUsuarios(BaseUserManager):
    def criar_usuario(self, nome_usuario, email, cpf_fiscal, password=None):
        if not cpf_fiscal:
            raise ValueError("Por favor informe um CPF")
        
        if not nome_usuario:
            raise ValueError("Por favor informe um nome")
        
        if not email:
            raise ValueError("Por favor informe um email")
        
        # Create the user object with necessary fields
        user = self.model(
            email=self.normalize_email(email),
            nome_usuario=nome_usuario,
            cpf_fiscal=cpf_fiscal,
        )
        
        user.set_password(password)
        user.save(using=self._db)
        return user

    def criar_superuser(self, nome_usuario, email, cpf_fiscal, password=None):
        user = self.criar_usuario(
            nome_usuario=nome_usuario,
            email=email,
            cpf_fiscal=cpf_fiscal,
            password=password
        )

        user.is_staff = True
        user.save(using=self._db)
        return user

class Fiscal(AbstractBaseUser):
    cpf_fiscal = models.CharField(primary_key=True, max_length=11)
    nome_usuario = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=55)
    is_active = models.BooleanField(db_column='ativo',default=True)     
    is_admin = models.BooleanField(db_column='staff',default=False) 

    objects = MinhaGestaoUsuarios()

    USERNAME_FIELD = 'nome_usuario'
    REQUIRED_FIELDS = ['email', 'cpf_fiscal']  

    class Meta:
        managed = False  
        db_table = 'fiscal'

    def __str__(self):
        return self.cpf_fiscal
    
    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin
    
class Tipo(models.Model):
    id_tipo = models.AutoField(primary_key=True)
    nome_tipo = models.CharField(max_length=20)
    capacidade_peso = models.DecimalField(decimal_places=2,max_digits=9)
    quantidade_eixos = models.PositiveSmallIntegerField()

    class Meta:
        managed = False
        db_table = 'tipo'

    def __str__(self):
        return str(self.id_tipo)
    
class Veiculo(models.Model):
    renavam = models.CharField(max_length=11,primary_key=True)
    id_tipo = models.ForeignKey(Tipo,db_column='id_tipo',null=True,on_delete=models.SET_NULL)
    placa = models.CharField(max_length=20)
    marca = models.CharField(max_length=20)
    modelo = models.CharField(max_length=20)
    cor = models.CharField(max_length=20)
    ano = models.CharField(max_length=4)
    rntrc = models.CharField(max_length=8)
    
    class Meta:
        managed = False
        db_table = 'veiculo'

    def __str__(self):
        return str(self.renavam)
    
class Frete(models.Model):
    id_frete = models.AutoField(primary_key=True)
    cpf_motorista = models.ForeignKey(Motorista,db_column='cpf_motorista',max_length=11, null=False,
    on_delete=models.SET_DEFAULT,blank=False,default="00000000000")  
    renavam = models.ForeignKey(Veiculo,db_column='renavam',max_length=11, null=False,
    on_delete=models.SET_DEFAULT,blank=False,default="00000000000")
    data_chegada = models.DateTimeField()
    data_saida = models.DateTimeField()
    distancia_rodagem = models.PositiveSmallIntegerField()
    valor_frete = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        managed = False
        db_table = 'frete'

    def __str__(self):
        return str(self.id_frete)
    
class Pagamento(models.Model):
    id_pagamento = models.AutoField(primary_key=True)
    cpf_fiscal = models.ForeignKey(Fiscal,db_column='cpf_fiscal', max_length=11,on_delete=models.SET_DEFAULT,default="000", null=False,blank=False)
    id_frete = models.ForeignKey(Frete,db_column='id_frete',on_delete=models.SET_NULL,null=True)
    taxa_desconto = models.DecimalField(max_digits=8,decimal_places=2)
    taxa_acrescimo = models.DecimalField(max_digits=8,decimal_places=2)
    valor_calculado = models.DecimalField(max_digits=12,decimal_places=2)
    data_pagamento = models.DateTimeField()
    
    class escolhas_status_pagamento(models.TextChoices):
        PENDENTE = "PE",_("Pendente")
        EM_TRANSFERENCIA = "TR",_("Em Transferência")
        PAGO = "PA",_("Pago")

    status_pagamento = models.CharField(
        max_length=2,
        choices=escolhas_status_pagamento.choices,
        default=escolhas_status_pagamento.PENDENTE,
    )
    
    class Meta:
        managed = False
        db_table = 'pagamento'

    def __str__(self):
        return str(self.id_pagamento)
    
class Acessa(models.Model):
    cpf_fiscal = models.ForeignKey(Fiscal,db_column='cpf_fiscal',max_length=11,on_delete=models.SET_DEFAULT,default="000", null=False,blank=False)
    id_tipo = models.ForeignKey(Tipo,db_column='id_tipo'    ,null=True,on_delete=models.SET_NULL) 
    data_alteracao = models.DateTimeField(primary_key=True)
    valor_km = models.DecimalField(max_digits=9,decimal_places=2)
    valor_tonelada = models.DecimalField(max_digits=9,decimal_places=2)
    valor_entrega = models.DecimalField(max_digits=12,decimal_places=2)
    
    class Meta:
        managed = False
        db_table = 'acessa'

    def __str__(self):
        return self.id_tipo, self.cpf_fiscal, self.data_alteracao
    
class Carga(models.Model):
    codigo_carga = models.AutoField(primary_key=True)
    id_frete = models.ForeignKey(Frete,db_column='id_frete',null=True,on_delete=models.SET_NULL,blank=True)
    peso = models.DecimalField(max_digits=9, decimal_places=2)
    valor_carga = models.DecimalField(max_digits=12, decimal_places=2)
    

    class Meta:
        managed = False
        db_table = 'carga'

    def __str__(self):
        return self.codigo_carga
    
class Entrega(models.Model):
    id_entrega = models.AutoField(primary_key=True)
    codigo_carga = models.ForeignKey(Carga, null=True,on_delete=models.SET_NULL,blank=True)
    peso_entrega = models.DecimalField(max_digits=9, decimal_places=2)
    valor_entrega = models.DecimalField(max_digits=12, decimal_places=2)
    cidade = models.CharField(max_length=30)
    dificuldade = models.BooleanField()
    cliente = models.CharField(max_length=30)

    class Meta:
        managed = False
        db_table = 'entrega'

    def __str__(self):
        return self.id_entrega

class EntregaDistribuidora(models.Model):
    id_entrega = models.ForeignKey(Entrega,on_delete=models.SET_NULL,null=True,blank=True)
    distribuidora = models.CharField(max_length=30,primary_key=True)

    class Meta:
        managed = False
        db_table = 'entrega_distribuidora'
        unique_together = (('id_entrega', 'distribuidora'))

    def __str__(self):
        return self.id_entrega, self.distribuidora

gerenciamento/templates/gerenciamento/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static%}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'gerenciamento/style.css'%}" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <a href="{% url 'gerenciamento:index' %}"><img class="ms-3" width="125" src="{% static 'gerenciamento/OPL-Fundo-Branco-1.png' %}" alt="logotipo"></a>
            </div>

            <div class="d-flex align-items-center me-1 ">
                <img width="28" src="{% static 'gerenciamento/user-solid.svg' %}" alt="pfoto">
                <p class="ms-3 mt-3 me-3" style="font-size: 142%;">{{user.nome_usuario}}</p>
            </div>
        </div>
    {% block content %}{% endblock content %}
</body>
</html>

gerenciamento/templates/gerenciamento/cadastrarc.html
{% extends 'gerenciamento/base.html' %}

{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<title>Cadastro do Cartão</title>

<div class="container">
    <div class="card mt-4 shadow-lg">
        <div class="card-header text-white text-center">
            <h2>CADASTRAR CARTÃO</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'gerenciamento:cadastrarc' %}" novalidate>
                {% csrf_token %}
                
                {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                
                <div class="row">
                    <div class="col-md-6">
                        <label for="id_nome" style="color: #6a708a; font-weight: 500;">Codigo do Cartão</label>
                        {% bootstrap_field form.codigo_cartao show_label=False show_errors=True placeholder="0235641598" %}
                    </div>
                    <div class="col-md-6">
                        <label for="id_cpf" style="color: #6a708a; font-weight: 500;">Cadastro de Pessoa Física (CPF)</label>
                        {% bootstrap_field form.cpf_motorista show_label=False show_errors=True placeholder="62005253501" %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label for="id_telefone" style="color: #6a708a; font-weight: 500;">Agência</label>
                        {% bootstrap_field form.agencia show_label=False show_errors=True placeholder="01231" %}
                    </div>
                    <div class="col-md-6">
                        <label for="id_cnh" style="color: #6a708a; font-weight: 500;">Numero da Conta</label>
                        {% bootstrap_field form.numero_conta show_label=False show_errors=True placeholder="456781" %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label for="id_dataAdmissao" style="color: #6a708a; font-weight: 500;">Data de Admissão</label>
                        {% bootstrap_field form.validade show_label=False show_errors=True %}
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-success btn-pequeno">SALVAR</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

gerenciamento/templates/gerenciamento/cadastrarm.html
{% extends 'gerenciamento/base.html' %}

{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<title>Cadastro do Motorista</title>

<div class="container">
    <div class="card mt-4 shadow-lg">
        <div class="card-header text-white text-center">
            <h2>CADASTRAR MOTORISTA</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'gerenciamento:cadastrarm' %}" novalidate>
                {% csrf_token %}
                
                <!-- Exibir erros globais de formulário, se houver -->
                {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                
                <div class="row">
                    <div class="col-md-6">
                        <label for="id_nome" style="color: #6a708a; font-weight: 500;">Nome Completo</label>
                        {% bootstrap_field form.nome show_label=False show_errors=True placeholder="Antônio Fonseca Novais" %}
                    </div>
                    <div class="col-md-6">
                        <label for="id_cpf" style="color: #6a708a; font-weight: 500;">Cadastro de Pessoa Física (CPF)</label>
                        {% bootstrap_field form.cpf_motorista show_label=False show_errors=True placeholder="62005253501" %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label for="id_telefone" style="color: #6a708a; font-weight: 500;">Telefone</label>
                        {% bootstrap_field form.telefone show_label=False show_errors=True placeholder="77981371290" %}
                    </div>
                    <div class="col-md-6">
                        <label for="id_cnh" style="color: #6a708a; font-weight: 500;">Registro da Carteira Nacional de Habilitação (CNH)</label>
                        {% bootstrap_field form.registro_cnh show_label=False show_errors=True placeholder="76211889218" %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label for="id_endereco" style="color: #6a708a; font-weight: 500;">Endereço</label>
                        {% bootstrap_field form.endereco show_label=False show_errors=True placeholder="Avenida Lapa, 1001" %}
                    </div>
                    <div class="col-md-6">
                        <label for="id_dataAdmissao" style="color: #6a708a; font-weight: 500;">Data de Admissão</label>
                        {% bootstrap_field form.data_admissao show_label=False show_errors=True %}
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-success btn-pequeno">SALVAR</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

gerenciamento/templates/gerenciamento/indexadmin.html
<!DOCTYPE html>
<html>
<head>`
    {% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>Tela Inicial do Administrador</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'gerenciamento/style.css'%}" rel="stylesheet">
</head>
<body>

    <div class="btn-group ms-4 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Motorista
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastrarm' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:pesquisarm' %}">Pesquisar</a></li>
            <li><hr class="dropdown-divider d-flex justify-content-center"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:editarm' %}">Editar</a></li>
            <li><hr class="dropdown-divider d-flex justify-content-center"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:excluirm' %}">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Cartão
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Pesquisar</a></li>
            <li><hr class="dropdown-divider "></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Excluir</a></li>
        </ul>
    </div>
    
    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Veículo
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tipo de Veículo
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Frete
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Pagamento
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Usuários
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastraru' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="#">Excluir</a></li>
        </ul>
    </div>
    
    <div class="d-flex align-items-center">

    <img width="400" src="{% static 'gerenciamento/OPL-Fundo-Branco-1.png' %}" class="mx-auto" alt="logo">
    
    </div>
    
    <div class="container-sm">
        <div class=" d-flex position-absolute bottom-0 start-0">
            <nav class="navbar">
                <div class="container">    
                    <ul class="nav-item dropup mt-4">
                        <a class="btn btn-secondary dropdown-toggle btn-pequeno shadow" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                        {{user.nome_usuario}}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'gerenciamento:password_reset' %}">Redefinir Senha</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'gerenciamento:logout' %}">Sair</a></li>
                        </ul>
                    </ul>

                    <img class="mt-2 mb-3" width="90" height="45" src="{% static 'gerenciamento/user-solid.svg' %}" alt="pfoto">
                
                    <p style="font-size: larger;">
                        Seja bem vindo, {{user.nome_usuario}}! <br>  
                        <strong>SISTEMA DE GERENCIAMENTO DE FRETES
                    </p>
                    
                </div>
                </nav>
            
        </div>
    </div>
</body>
</html>