gerenciamento/urls.py
"""Define os URL patterns de gerenciamento."""

from django.urls import path
from . import views
from gerenciamento.views import ResetPasswordView
from django.contrib.auth import views as auth_views

app_name = 'gerenciamento'

urlpatterns = [
    # Pagina inicial
    path('', views.index, name='index'),
    # Pagina inicial admin
    path('iadmin/', views.indexadmin, name='indexadmin'),
    # Pagina de cadastro dos motoristas
    path('cadastrarm/', views.cadastrarm, name='cadastrarm'),
    # Pagina de sucesso
    path('sucesso/', views.sucesso, name='sucesso'),
    # Pagina de sucesso
    path('pesquisarm/', views.pesquisarm, name='pesquisarm'),
    # Pagina de edição dos motoristas
    path('editarm/', views.editarm, name='editarm'),
    # Pagina inserção dos dados da edição dos motoristas
    path('formeditarm/<str:cpf_motorista>/', views.formeditarm, name='formeditarm'),
    # Pagina de exclusão dos motoristas
    path('excluirm/', views.excluirm, name='excluirm'),
    # Pagina de exclusão dos motoristas
    path('excluirm/<str:cpf_motorista>/', views.formexcluirm, name='formexcluirm'),
    # Pagina de cadastro dos usuarios
    path('cadastraru/', views.cadastraru, name='cadastraru'),
    # Pagina de login
    path('login/', views.login_view, name='login'),
    # Pagina de logout
    path('logout/', views.logout_view, name='logout'),
    # Pagina de inserção do email para a redefinição de senha
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    # Pagina de redefinição da senha do usuario
    path('password-reset-confirm/<str:email>/', views.custom_password_reset_confirm, name='redefinir_senha'),
    # Pagina de sucesso da redefinação da senha
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='gerenciamento/login/password_reset_complete.html'),
    name='password_reset_complete'),
    # Pagina de cadastro dos cartões
    path('cadastrarc/', views.cadastrarc, name='cadastrarc'),
    # Pagina de pesquisa dos cartões
    path('pesquisarc/', views.pesquisarc, name='pesquisarc'),
    # Pagina de edição dos cartões
    path('editarc/', views.editarc, name='editarc'),
    # Pagina inserção dos dados da edição dos cartões
    path('formeditarc/<str:numero_conta>/', views.formeditarc, name='formeditarc'),
    # Pagina de exclusão dos cartões
    path('excluirc/', views.excluirc, name='excluirc'),
    # Pagina de exclusão dos cartões
    path('excluirc/<str:numero_conta>/', views.formexcluirc, name='formexcluirc'),
    # Pagina de pesquisa dos usuarios
    path('pesquisaru/', views.pesquisaru, name='pesquisaru'),
    # Pagina de edição dos usuarios
    path('editaru/', views.editaru, name='editaru'),
    # Pagina inserção dos dados da edição dos usuarios
    path('formeditaru/<str:cpf_fiscal>/', views.formeditaru, name='formeditaru'),
    # Pagina de exclusão dos usuarios
    path('excluiru/', views.excluiru, name='excluiru'),
    # Pagina de exclusão dos usuarios
    path('excluiru/<str:cpf_fiscal>/', views.formexcluiru, name='formexcluiru'),
    # Pagina de cadastro dos tipos de veículos
    path('cadastrart/', views.cadastrart, name='cadastrart'),
    # Pagina de pesquisa dos tipos de veículos
    path('pesquisart/', views.pesquisart, name='pesquisart'),
    # Pagina de edição dos tipos de veículos
    path('editart/', views.editart, name='editart'),
    # Pagina inserção dos dados da edição dos tipos de veículos
    path('formeditart/<str:id_tipo>/', views.formeditart, name='formeditart'),
    # Pagina de exclusão dos tipos de veículos
    path('excluirt/', views.excluirt, name='excluirt'),
    # Pagina de exclusão dos motoristas
    path('excluirt/<str:id_tipo>/', views.formexcluirt, name='formexcluirt'),
    # Pagina de cadastro dos veículos
    path('cadastrarv/', views.cadastrarv, name='cadastrarv'),
    # Pagina de pesquisa dos tipos de veículos
    path('pesquisarv/', views.pesquisarv, name='pesquisarv'),
    # Pagina de edição dos tipos de veículos
    path('editarv/', views.editarv, name='editarv'),
    # Pagina inserção dos dados da edição dos tipos de veículos
    path('formeditarv/<str:renavam>/', views.formeditarv, name='formeditarv'),
    # Pagina de exclusão dos tipos de veículos
    path('excluirv/', views.excluirv, name='excluirv'),
    # Pagina de exclusão dos motoristas
    path('excluirv/<str:renavam>/', views.formexcluirv, name='formexcluirv'),
    # Pagina de cadastro dos veículos
    path('cadastrarf/', views.cadastrarf, name='cadastrarf'),
    # Pagina de pesquisa dos tipos de veículos
    path('pesquisarf/', views.pesquisarf, name='pesquisarf'),
    # Pagina de edição dos tipos de veículos
    path('editarf/', views.editarf, name='editarf'),
    # Pagina inserção dos dados da edição dos tipos de veículos
    path('formeditarf/<str:id_frete>/', views.formeditarf, name='formeditarf'),
    # Pagina de exclusão dos tipos de veículos
    path('excluirf/', views.excluirf, name='excluirf'),
    # Pagina de exclusão dos motoristas
    path('excluirf/<str:id_frete>/', views.formexcluirf, name='formexcluirf'),
    # Pagina de cadastro dos veículos
    path('cadastrarp/', views.cadastrarp, name='cadastrarp'),
    # Pagina de pesquisa dos tipos de veículos
    path('pesquisarp/', views.pesquisarp, name='pesquisarp'),
    # Pagina de edição dos tipos de veículos
    path('editarp/', views.editarp, name='editarp'),
    # Pagina inserção dos dados da edição dos tipos de veículos
    path('formeditarp/<str:id_pagamento>/', views.formeditarp, name='formeditarp'),
    # Pagina de exclusão dos tipos de veículos
    path('excluirp/', views.excluirp, name='excluirp'),
    # Pagina de exclusão dos motoristas
    path('excluirp/<str:id_pagamento>/', views.formexcluirp, name='formexcluirp'),
]

sgf_project/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerenciamento.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gerenciamento/views.py
from django.shortcuts import render, redirect
from .forms import FreteForm, MotoristaForm, CartaoForm, PagamentoForm, RegistroFiscalForm, TipoForm, VeiculoForm
from .models import Acessa, Carga, Motorista, Cartao, Frete, Fiscal, Pagamento, Tipo, Veiculo
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

@login_required
def index(request):
    """A pagina inicial dos fiscais"""
    return render(request, 'gerenciamento/base/index.html')

@staff_member_required
def indexadmin(request):
    """A pagina inicial do administrador"""
    return render(request, 'gerenciamento/base/indexadmin.html')

@login_required
def cadastrarm(request):
    if request.method != 'POST':
        form = MotoristaForm()
    else:
        form = MotoristaForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('gerenciamento:sucesso')  
    
    context = {'form': form}
    return render(request, 'gerenciamento/motorista/cadastrarm.html', context)

@login_required
def sucesso(request):
    return render(request, 'gerenciamento/base/sucesso.html')

@login_required
def pesquisarm(request):
    motoristas = Motorista.objects.all().order_by('nome')
    
    context = {
        'motoristas': motoristas
    }
    return render(request, 'gerenciamento/motorista/pesquisarm.html', context)

@login_required
def editarm(request):
    motoristas = Motorista.objects.all().order_by('nome')
    
    context = {
        'motoristas': motoristas
    }
    return render(request, 'gerenciamento/motorista/editarm.html', context)

@login_required
def formeditarm(request, cpf_motorista):
    motoristas = Motorista.objects.get(cpf_motorista=cpf_motorista)
    
    form = MotoristaForm(request.POST or None,instance=motoristas)
    
    if form.is_valid():
        form.save()
        return redirect('gerenciamento:sucesso')  
    
    context = {'form': form, 'motoristas': motoristas}
    return render(request, 'gerenciamento/motorista/formeditarm.html', context)

@login_required
def excluirm(request):
    motoristas = Motorista.objects.all().order_by('nome')
    
    context = {
        'motoristas': motoristas
    }
    return render(request, 'gerenciamento/motorista/excluirm.html', context)

@login_required
def formexcluirm(request,cpf_motorista):

    motoristas = Motorista.objects.get(cpf_motorista=cpf_motorista)
    
    Cartao.objects.filter(cpf_motorista=cpf_motorista).update(cpf_motorista=None)
    
    Frete.objects.filter(cpf_motorista=cpf_motorista).update(cpf_motorista=None)

    motoristas.delete()
    
    return render(request,'gerenciamento/base/sucesso.html')
    
@staff_member_required
def cadastraru(request):
    if request.method != 'POST':
        form = RegistroFiscalForm()
    else:
        form = RegistroFiscalForm(request.POST)
        if form.is_valid():
            # Create the user but don't save to the database yet
            user = form.save(commit=False)
            # Set the hashed password and save the user
            user.set_password(form.cleaned_data['password'])
            
            user.is_active = True
            user.is_admin = False
            
            user.save()
            return redirect('gerenciamento:sucesso')

    return render(request, 'gerenciamento/usuario/cadastraru.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        nome_usuario = request.POST.get('nome_usuario')
        password = request.POST.get('password')

        user = authenticate(request, nome_usuario=nome_usuario, password=password)

        if user is not None:
            login(request, user)
            user.last_login = timezone.now()  # Update last_login
            user.save()  # Save the user to update the last_login
            
            if user.is_staff:
                return redirect('gerenciamento:indexadmin')  # Redirect to homepage after login
            else:
                return redirect('gerenciamento:index')  # Redirect to homepage after login
            
            
        else:
            messages.error(request, "Nome de usuario ou senha inválidos, Tente novamente.")  # Update message to reflect changes

    return render(request, 'gerenciamento/login/login.html')

def logout_view(request):
    logout(request)
    return redirect('gerenciamento:login')  # Redirect to the login page after logging out

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'gerenciamento/login/password_reset.html'
    email_template_name = 'gerenciamento/login/password_reset_email.html'
    subject_template_name = 'gerenciamento/login/password_reset_subject.txt'
    success_message = "Um email foi enviado com as intruções para a redefinição da sua senha, " \
    "se uma conta com o email enviado existir você deve recebe-lo." \
    " Se ainda não o recebeu confirme o email digitado e verifique a caixa de spam." 
    success_url = reverse_lazy('gerenciamento:login')
    
def custom_password_reset_confirm(request, email):

    user = Fiscal.objects.get(email=email)
    
    form = RegistroFiscalForm(request.POST or None,instance=user)

    if form.is_valid():
        # Create the user but don't save to the database yet
        user = form.save(commit=False)
        # Set the hashed password and save the user
        user.set_password(form.cleaned_data['password'])
        
        user.is_active = True
        user.is_admin = False
        user.save()
        return redirect('gerenciamento:password_reset_complete')  

    context = {'form': form, 'user': user}
    
    return render(request, 'gerenciamento/login/editarsenha.html', context)

@login_required
def cadastrarc(request):
    if request.method != 'POST':
        form = CartaoForm()
        form.fields['cpf_motorista'].queryset = Motorista.objects.all()
        form.fields['cpf_motorista'].label_from_instance = lambda obj: f"{obj.cpf_motorista} - {obj.nome}"
    else:
        form = CartaoForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('gerenciamento:sucesso')  
    
    context = {'form': form}

    return render(request, 'gerenciamento/cartao/cadastrarc.html', context)

@login_required
def pesquisarc(request):
    cartoes = Cartao.objects.select_related('cpf_motorista').all().order_by('cpf_motorista')
    
    context = {
        'cartoes': cartoes
    }
    return render(request, 'gerenciamento/cartao/pesquisarc.html', context)

@login_required
def editarc(request):
    cartoes = Cartao.objects.select_related('cpf_motorista').all().order_by('cpf_motorista')
    
    context = {
        'cartoes': cartoes
    }
    return render(request, 'gerenciamento/cartao/editarc.html', context)

@login_required
def formeditarc(request, numero_conta):
    cartoes = Cartao.objects.get(numero_conta=numero_conta)
    
    form = CartaoForm(request.POST or None,instance=cartoes)
    form.fields['cpf_motorista'].queryset = Motorista.objects.all()
    form.fields['cpf_motorista'].label_from_instance = lambda obj: f"{obj.cpf_motorista} - {obj.nome}"
    
    if form.is_valid():
        form.save()
        return redirect('gerenciamento:sucesso')  
    
    context = {'form': form, 'cartoes': cartoes}
    return render(request, 'gerenciamento/cartao/formeditarc.html', context)

@login_required
def excluirc(request):
    cartoes = Cartao.objects.select_related('cpf_motorista').all().order_by('cpf_motorista')
    
    context = {
        'cartoes': cartoes
    }
    return render(request, 'gerenciamento/cartao/excluirc.html', context)

@login_required
def formexcluirc(request,numero_conta):
    cartao = Cartao.objects.get(numero_conta=numero_conta)
    
    cartao.delete()
    
    return render(request,'gerenciamento/base/sucesso.html')

@staff_member_required
def pesquisaru(request):
    usuarios = Fiscal.objects.all().order_by('nome_usuario')
    
    context = {
        'usuarios': usuarios
    }
    return render(request, 'gerenciamento/usuario/pesquisaru.html', context)

@staff_member_required
def editaru(request):
    usuarios = Fiscal.objects.all().order_by('nome_usuario')
    
    context = {
        'usuarios': usuarios
    }
    
    return render(request, 'gerenciamento/usuario/editaru.html', context)

@staff_member_required
def formeditaru(request, cpf_fiscal):
    usuario = Fiscal.objects.get(cpf_fiscal=cpf_fiscal)
    
    if request.method == 'POST':
        form = RegistroFiscalForm(data=request.POST, instance=usuario)
        form.fields.pop('password', None)
        form.fields.pop('password_confirm', None)
        
        if form.is_valid():
            form.save()
            return redirect('gerenciamento:sucesso')
    else:
        form = RegistroFiscalForm(instance=usuario)
        form.fields.pop('password', None)
        form.fields.pop('password_confirm', None)

    context = {'form': form, 'usuario': usuario}
    return render(request, 'gerenciamento/usuario/formeditaru.html', context)

@staff_member_required
def excluiru(request):
    usuarios = Fiscal.objects.all().order_by('nome_usuario')
    
    context = {
        'usuarios': usuarios
    }
    return render(request, 'gerenciamento/usuario/excluiru.html', context)

@staff_member_required
def formexcluiru(request, cpf_fiscal):
    usuario = Fiscal.objects.get(cpf_fiscal=cpf_fiscal)
    
    Pagamento.objects.filter(cpf_fiscal=cpf_fiscal).update(cpf_fiscal=None)
    
    Acessa.objects.filter(cpf_fiscal=cpf_fiscal).update(cpf_fiscal=None)
    
    usuario.delete()
    
    return render(request,'gerenciamento/base/sucesso.html')

@login_required
def cadastrart(request):

gerenciamento/templates/gerenciamento/base/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static%}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'gerenciamento/style.css'%}" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                {% if user.is_admin %}
                    <a href="{% url 'gerenciamento:indexadmin' %}"><img class="ms-3" width="125" src="{% static 'gerenciamento/OPL-Fundo-Branco-1.png' %}" alt="logotipo"></a>
                {% else %}
                    <a href="{% url 'gerenciamento:index' %}"><img class="ms-3" width="125" src="{% static 'gerenciamento/OPL-Fundo-Branco-1.png' %}" alt="logotipo"></a>
                {% endif %}          
                </div>
            <div class="d-flex align-items-center me-1 ">
                <img width="28" src="{% static 'gerenciamento/user-solid.svg' %}" alt="pfoto">
                <p class="ms-3 mt-3 me-3" style="font-size: 142%;">{{user.nome_usuario}}</p>
            </div>
        </div>
    {% block content %}{% endblock content %}
</body>
</html>

gerenciamento/templates/gerenciamento/base/indexadmin.html
<!DOCTYPE html>
<html>
<head>`
    {% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>Tela Inicial do Administrador</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'gerenciamento/style.css'%}" rel="stylesheet">
</head>
<body>

    <div class="btn-group ms-4 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Motorista
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastrarm' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:pesquisarm' %}">Pesquisar</a></li>
            <li><hr class="dropdown-divider d-flex justify-content-center"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:editarm' %}">Editar</a></li>
            <li><hr class="dropdown-divider d-flex justify-content-center"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:excluirm' %}">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Cartão
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastrarc' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:pesquisarc' %}">Pesquisar</a></li>
            <li><hr class="dropdown-divider "></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:editarc' %}">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:excluirc' %}">Excluir</a></li>
        </ul>
    </div>
    
    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Veículo
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastrarv' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:pesquisarv' %}">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:editarv' %}">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:excluirv' %}">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tipo de Veículo
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastrart' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:pesquisart' %}">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:editart' %}">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:excluirt' %}">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Frete
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastrarf' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:pesquisarf' %}">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:editarf' %}">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:excluirf' %}">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Pagamento
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastrarp' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:pesquisarp' %}">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:editarp' %}">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:excluirp' %}">Excluir</a></li>
        </ul>
    </div>

    <div class="btn-group ms-2 mt-4 shadow">
        <button class="btn btn-secondary btn-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Usuários
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:cadastraru' %}">Cadastrar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:pesquisaru' %}">Pesquisar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:editaru' %}">Editar</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex justify-content-center" href="{% url 'gerenciamento:excluiru' %}">Excluir</a></li>
        </ul>
    </div>
    
    <div class="d-flex align-items-center">

    <img width="400" src="{% static 'gerenciamento/OPL-Fundo-Branco-1.png' %}" class="mx-auto" alt="logo">
    
    </div>
    
    <div class="container-sm">
        <div class=" d-flex position-absolute bottom-0 start-0">
            <nav class="navbar">
                <div class="container">    
                    <ul class="nav-item dropup mt-4">
                        <a class="btn btn-secondary dropdown-toggle btn-pequeno shadow" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                        {{user.nome_usuario}}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'gerenciamento:password_reset' %}">Redefinir Senha</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'gerenciamento:logout' %}">Sair</a></li>
                        </ul>
                    </ul>

                    <img class="mt-2 mb-3" width="90" height="45" src="{% static 'gerenciamento/user-solid.svg' %}" alt="pfoto">
                
                    <p style="font-size: larger;">
                        Seja bem vindo, {{user.nome_usuario}}! <br>  
                        <strong>SISTEMA DE GERENCIAMENTO DE FRETES
                    </p>
                    
                </div>
                </nav>
            
        </div>
    </div>
</body>
</html>

gerenciamento/templates/gerenciamento/base/sucesso.html
{% extends 'gerenciamento/base/base.html' %}

{% block content %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<title>Pagina de Sucesso</title>

<div class="container mt-5">
    <h2>Operação realizada com sucesso!</h2>
    {% if user.is_admin %}
        <a href="{% url 'gerenciamento:indexadmin' %}">Retornar a pagina inicial<a>
    {% else %}
        <a href="{% url 'gerenciamento:index' %}">Retornar a pagina inicial<a>
    {% endif %}   
</div>

{% endblock content %}